name: 3sixD
favicon: null
layout_spectrum: 0.88537
typography_spectrum: 0.2813
title: '3sixD | Social | Staffing | Consulting | Technology'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ec1c24'
    - '#ff0000'
    - '#aa0000'
    - '#800000'
    - '#000000'
  brandStrength: 0.5625
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
