name: 3sixD
favicon: null
layout_spectrum: 0.11300885281525552
typography_spectrum: 0.019463239004835486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5319216672796756
  lightness: 0.8049171345774084
  saturation: 0.3853569442871958
  rhythmicContrast: 0.6420078109949827
purpose: []
